apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app: argocd
    app.kubernetes.io/instance: inventory
    service: inventory
    version: v2
  name: inventory-sa
  namespace: sealedsecretstest